name: axum-web-app
services:
  - name: axum-web-app-service
    image:
      name: axum-web-app-image
      source: dockerfile
    ports:
      - name: http
        port: 8080
    healthchecks:
      - name: http
        protocol: HTTP
        path: /
        port: 8080
        interval: 10s
        timeout: 2s
        retries: 3
